name: Update Repository List

on:
  schedule:
    - cron: '0 0 * * *'  # daily
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Fetch Repositories
        env:
          GH_USERNAME: ${{ github.repository_owner }}
        run: |
          mkdir -p _data

          # Fetch repos
          curl -s "https://api.github.com/users/$GH_USERNAME/repos?per_page=100&type=public" > repos.json

          echo "[" > _data/repos.json
          COUNT=0

          jq -c '.[]' repos.json | while read repo; do
            NAME=$(echo "$repo" | jq -r '.name')
            HTML_URL=$(echo "$repo" | jq -r '.html_url')
            DESCRIPTION=$(echo "$repo" | jq -r '.description')

            jq -n \
              --arg name "$NAME" \
              --arg html_url "$HTML_URL" \
              --arg description "$DESCRIPTION" \
              '{name: $name, html_url: $html_url, description: $description}' >> _data/repos.json

            COUNT=$((COUNT + 1))
            if [ "$COUNT" -lt "$(jq length repos.json)" ]; then
              echo "," >> _data/repos.json
            fi
          done

          echo "]" >> _data/repos.json

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add _data/repos.json
          git commit -m "Update repos list" || echo "No changes"
          git push
