name: Update Repo Lists

on:
  schedule:
    - cron: '0 0 * * *'  # Daily
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Fetch listed repos by full name
        run: |
          mkdir -p _data
          LISTS_FILE="_data/repo_lists.yml"
          OUTPUT="_data/repos.json"

echo "[" > "$OUTPUT"

REPO_NAMES=$(yq e '.[].[]' "$LISTS_FILE" | sort | uniq)
TOTAL=$(echo "$REPO_NAMES" | wc -l)
COUNT=0

echo "$REPO_NAMES" | while read full_name; do
  RESPONSE=$(curl -s "https://api.github.com/repos/$full_name")

  NAME=$(echo "$RESPONSE" | jq -r '.name')
  FULL_NAME=$(echo "$RESPONSE" | jq -r '.full_name')
  HTML_URL=$(echo "$RESPONSE" | jq -r '.html_url')
  DESCRIPTION=$(echo "$RESPONSE" | jq -r '.description')

  if [ "$HTML_URL" != "null" ]; then
    if [ "$COUNT" -ne 0 ]; then
      echo "," >> "$OUTPUT"
    fi

    jq -n \
      --arg name "$NAME" \
      --arg full_name "$FULL_NAME" \
      --arg html_url "$HTML_URL" \
      --arg description "$DESCRIPTION" \
      '{name: $name, full_name: $full_name, html_url: $html_url, description: $description}' >> "$OUTPUT"

    COUNT=$((COUNT + 1))
  fi
done

echo "]" >> "$OUTPUT"


      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add _data/repos.json
          git commit -m "Update full repo list" || echo "No changes"
          git push
